### ISSUE TITLE
Por favor indique o link para o trabalho de Testes de Software(peso 5)

### ISSUE THREAD

**Issue by RafaelGorski** [CamoesEngenhariaDeSoftware/Leandro-Lima#1]
@lesamuka 
Por favor indique o link para o trabalho de Testes de Software(peso 5)

**Comment by lesamuka** [comment]
Boa noite professor, tentei mandar e-mail pelo sistema Camões, mas já foi bloqueado meu acesso,
Tive que trancar minha matrícula devido a mudança de horários no serviço, ficaria grato se o Sr avisasse os dois colegas que iriam fazer o trabalho de apresentação comigo.
Desde já muito obrigado professor, as aulas do Sr estão de parabéns.

Em 8 de out de 2018 11:46, Rafael Gorski <notifications@github.com> escreveu:

@lesamuka<https://github.com/lesamuka>
Por favor indique o link para o trabalho de Testes de Software(peso 5)
